### ISSUE TITLE
Use proper optimisation settings for the D compiler.

### ISSUE THREAD

**Issue by maxhaton** [ddcovery/expressive_sort#1]
You are currently passing `--release` to the sorted.d program not the compiler.

dmd also produces terrible code, use ldc2 instead to utilize LLVM.

## If you do it right: 

Results from my machine: 
### rdmd with just `--release`
```
# D
1.0M: 2079 ms
1.5M: 3278 ms
3.0M: 6798 ms
6.0M: 13876 ms
```
### rdmd with optimizations turned on explicitly (`rdmd -O --release sorted.d`)
```
# D
1.0M: 1560 ms
1.5M: 2433 ms
3.0M: 5046 ms
6.0M: 10667 ms
```
### Using LLVM (`rdmd --compiler=ldc2 -release -O5`)
```
# D
1.0M: 543 ms
1.5M: 740 ms
3.0M: 1547 ms
6.0M: 3170 ms
```

### Everything LLVM has to give (`rdmd --compiler=ldc2 -release -O5 -enable-cross-module-inlining -flto=full sorted.d`)
```
# D
1.0M: 478 ms
1.5M: 717 ms
3.0M: 1485 ms
6.0M: 3080 ms
```

**Comment by maxhaton** [comment]
should be `-release`, not `--release` sorry.

**Comment by ddcovery** [comment]
I found that **ldc2 1.23.0** (from snap package) generated code is faster than the **1.20.1** version (from apt repositories): about (5%-10% faster).

In the two cases **-flto=full** option fails, 

For "snap" version:
`/usr/bin/ld.gold: error: /snap/ldc2/168/lib/LLVMgold-ldc.so: could not load plugin library: /snap/core/current/lib/x86_64-linux-gnu/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
`
In my machine there is not difference between adding/removing **-enable-corss-module-inlining**, but I will include it

It is difficult to compare some flags results because time varies between executions (same test gives different results: +-15%).  For better performance measurement, each test will run 5 times (console output is the average of each test)... this is specially annoying with the python test (how the hell it is so slow?... javascript really performs nice in comparison) , but gives us accurate values.

**Comment by maxhaton** [comment]
If you want to give a realistic portrayal of the results, I would use some kind of histogram or box and whisker plot because the way caching effects some benchmarks means that the data can be mostly in the tails of the distribution and the mean is therefore not always useful.

I'm not sure why your link time opt fails, incompatible glibc versions? I didn't use a snap distribution of ldc, could be that.

**Comment by ddcovery** [comment]
Sorry max, but I'm not sure I understand you.

New version use a new set of data in each measurement to avoid "side" optimization effects (In any case, comparing results of 5 internal test iterations using the same set of data shows no appreciable "time" correlation).

May be, best option will be to generate some data sets (on files) and run tests on them one by one (1 execution -> 1 test) leaving in test.sh the responsibility of executing each test N times.
